print("How much do you earn per hour? ")
hour = input()
print(hour)
print("So you earn " + hour + " an hour right?" )
print("And how many hours do you work monthly?")
worked = input()
print("You work " + worked + " hours a month and you earn " + hour + " for every hour")
salary = float(hour + worked)
ir = float(salary * 11) /100
inss = float(ir * 8/100)
sindicato = float(inss * 5/100)
total = float(salary - ir - inss - sindicato)
print ("Your salary is " + str(salary))
print ("Your salary with IR discount is " + str(ir))
print ("Your salary with INSS discount is " + str(inss))
print ("Your salary with sindicato discount is " + str(sindicato))
print ("Your salary with with everything is " + str(total))
